name: "[Check] go validation"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read

jobs:
  validate-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.0
    - name: Build
      run: go build -v . && go build -v ./...
    - name: Test
      run: go test -v ./...
    - name: Lint
      uses: golangci/golangci-lint-action@v6.5.0
    - name: Version check
      run: diff -u VERSION <(grep "var version = " trezord.go | cut -f 2 -d '"')
